#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MSPy Package
============
A package for mass spectrometry data analysis.
"""

from .py_calculations import (
    MBox,
    MNoise,
    array_print,
    signal_median,
    signal_interpolate_y,
    signal_interpolate_x,
    signal_locate_x,
    signal_locate_max_y,
    signal_box,
    signal_intensity,
    signal_centroid,
    signal_width,
    signal_area,
    signal_noise,
    signal_local_maxima,
    signal_crop,
    signal_offset,
    signal_multiply,
    signal_normalize,
    signal_smooth_ma,
    formula_composition,
    signal_gaussian,
    signal_lorentzian,
    signal_gausslorentzian,
    signal_profile,
    signal_profile_to_raster,
)
from .mod_basics import delta, mz, md, nominalmass, rdbe, frules
from .mod_formulator import formulator
from .mod_pattern import pattern
from .obj_compound import compound
from .blocks import (
    element,
    monomer,
    enzyme,
    fragment,
    modification,
    elements,
    monomers,
    enzymes,
    fragments,
    modifications,
    loadMonomers,
    loadEnzymes,
    loadModifications,
    saveMonomers,
    saveEnzymes,
    saveModifications,
)

__version__ = "1.0.0"

__all__ = [
    "MBox",
    "MNoise",
    "array_print",
    "signal_median",
    "signal_interpolate_y",
    "signal_interpolate_x",
    "signal_locate_x",
    "signal_locate_max_y",
    "signal_box",
    "signal_intensity",
    "signal_centroid",
    "signal_width",
    "signal_area",
    "signal_noise",
    "signal_local_maxima",
    "signal_crop",
    "signal_offset",
    "signal_multiply",
    "signal_normalize",
    "signal_smooth_ma",
    "formula_composition",
    "signal_gaussian",
    "signal_lorentzian",
    "signal_gausslorentzian",
    "signal_profile",
    "signal_profile_to_raster",
    "delta",
    "mz",
    "md",
    "nominalmass",
    "rdbe",
    "frules",
    "formulator",
    "pattern",
    "compound",
    "element",
    "monomer",
    "enzyme",
    "fragment",
    "modification",
    "elements",
    "monomers",
    "enzymes",
    "fragments",
    "modifications",
    "loadMonomers",
    "loadEnzymes",
    "loadModifications",
    "saveMonomers",
    "saveEnzymes",
    "saveModifications",
]
